chain: "bsc"
interval: 1m
clientURL: "https://bsc-dataseed.binance.org/"
ethConfirmBlockNumber: 2
ethGasPriceLimit: 1000000001
grpcPort: 7203
grpcProxyPort: 8203
privateKey: ""
slackWebHook: "" 
validators:
  - withPayload: true
    address: "0x95C6F6Af2c0Fa069768203FDa963d7626efC794a"
    cashiers:
      - address: "0xa016f866a606221E9C9E6ab3a942Bfc81F6074f4"
unwrappers:
  0xC365d086642efB5599b2D9639b7029AbFcD5b6Bf:
    # FOR
    0x7e544f2fEDDc69b1cB12555779c824CFe100ee34: "0x658A109C5900BC6d2357c87549B651670E5b0539"
    # BioShib
    0xa0CB9c8e470EC591dd7f5De650af9468EE6f7d5A: "0xab951271F025D93c278516e3d131e017e8a3089D"
    # THC
    0x8Dfb1099C53f634BEcf3C98aE19eB1BAA1b37D43: "0x56083560594E314b5cDd1680eC6a493bb851BBd8"
    # DRF
    0x02dF5253Bc4EfC9F8f744133Ff99981b18Df0473: "0x9400Aa8eb5126d20CDE45C7822836BFB70F19878"
    # XPIN
    0x486501A021514ac9A3E5023B5eA4A69a93b725ca: "0xD955c9bA56Fb1AB30e34766e252A97ccCE3D31A6"
    # NB
    0xD0781be7335ec2C820bD3F9687dDe809892d985e: "0xc2bD425A63800731E3Ae42b6596BDD783299fCb1"
database:
  uri: "root:kdfjjrU64fjK58H@tcp(database:3306)/relayer?parseTime=true"
  driver: "mysql"
transferTableName: "bsc_transfers"
witnessTableName: "bsc_witnesses"
